name: Continuous Delivery

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Create SSH key
        run: |
          mkdir -p ~/.ssh/
          echo "${SSH_PRIVATE_KEY}" > ~/.ssh/id_ed25519
          sudo chmod 600 ~/.ssh/id_ed25519
          echo "${SSH_KNOWN_HOSTS}" > ~/.ssh/known_hosts
        shell: bash
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SSH_KNOWN_HOSTS: ${{ secrets.SSH_KNOWN_HOSTS }}
      - name: Copy files to server
        run: |
          scp ./nginx/nginx.conf ${SSH_USER}@${SSH_HOST}:/etc/nginx/sites-available/nginx.conf
          scp -r ./static ${SSH_USER}@${SSH_HOST}:/var/www
        shell: bash
        env:
          SSH_USER: ${{ secrets.SSH_USER }}
          SSH_HOST: ${{ secrets.SSH_HOST }}
      - name: Restart web server
        run: |
          ssh ${SSH_USER}@${SSH_HOST} /bin/bash << EOF
            printf "=> Moving static files...\n"
            echo ${SSH_PASSWORD} | sudo -S rm -r /var/www/html > /dev/null 2>&1
            sudo mv /var/www/static /var/www/html
          
            printf "=> Restarting web server...\n"
            sudo systemctl restart nginx
          EOF
        shell: bash
        env:
          SSH_USER: ${{ secrets.SSH_USER }}
          SSH_HOST: ${{ secrets.SSH_HOST }}
          SSH_PASSWORD: ${{ secrets.SSH_PASSWORD }}
